### PR TITLE
Patch php 8.2

### PR DESCRIPTION
**Pull request by thestalnakergroup**

### CODE REVIEW

**Review by daemionfox — APPROVED** [review]
Changes look good, please merge these to stop deprecation warnings from XMLWriter

**Comment by FutureShirtsDevs** [comment]
I would love for this to get merged to stop deprecation warnings in 8.1. Only thing I see is startElement should "return" parent::startElement($name);

**Comment by thestalnakergroup** [comment]
image
Getting this to merge. Looks like someone with write access have to approve?

**Comment by thestalnakergroup** [comment]
@daemionfox can you merge this in?

**Comment by thestalnakergroup** [comment]
@jimmymcpeter any chance we can get this merged?

**Comment by jimmymcpeter** [comment]
> @jimmymcpeter any chance we can get this merged?

Unfortunately I don't work in this area anymore.  Let me reach out to some folks and see if they can help.

**Comment by thestalnakergroup** [comment]
Thank you!

[photograph]

Billy Stalnaker
Owner

M: (910) 232-4703
E: ***@***.***
The Stalnaker Group
stalnakergroup.com<http://stalnakergroup.com/>

________________________________

**Comment by thestalnakergroup** [comment]
@cstretton, merged master to get the return in there. Also, asked ChatGPT to refactor the function you referenced. I never got any issues with this function, and I'm not exactly sure how to test to make sure it works correctly, but it looks right to me. 

Thanks for your help!

**Comment by williamatpaper** [comment]
Haha crap. I thought you were THE guy.

**Comment by rijnhard** [comment]
@jimmymcpeter you find anyone internally who can approve/test/merge?

**Comment by rijnhard** [comment]
> > @jimmymcpeter any chance we can get this merged?
> 
> Unfortunately I don't work in this area anymore. Let me reach out to some folks and see if they can help.

Just following up here if you could get this through to the right people?

**Comment by jimmymcpeter** [comment]
@rijnhard I think your best bet is to fork the repo, make your fixes there, and update your composer.json to load from your repo instead -- https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository

**Review by tim-miller-sage — APPROVED** [review]

**Pull request merged**
